### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by skubiak2000** [skubiak2000/markdown-portfolio#2]
- [x] Turn on GitHub Pages
- [x] Outline my portfolio
- [ ] Introduce myself to the world
